### PR TITLE
Move automation to github actions

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Moved automation to github actions

# Need Review By (Date)
- 

# Urgency
- 

# Steps to Test

### CODE REVIEW

**Comment by pookmish** [comment]
If you plan to update the profile with the latest from 9.x Stanford profile soon you can ignore this.

**Review by joegl — APPROVED** [review]
Thanks @pookmish ! I don't plan to pull from the `stanford_profile` development branches if I can avoid it, so this is really helpful. The CircleCI test is only failing because no config exists and the intention here is to remove CircleCI, so I'm going to ignore that "failed" test.

I'm also going to remove the CircleCI webhooks and secrets from the repo, and "stop building" it in the Project Settings for CircleCI. Let me know if there's anything I should do to fully unhook CircleCI.

**Comment by pookmish** [comment]
Yep. "Stop Building" and remove adjust the protected branches in the repo settings. g2g. thanks.

**Comment by joegl** [comment]
What branch protections should I adjust? I currently only have protection set up on the `1.x` branch, which requires an approving PR review and all tests to pass before merging into it.

**Comment by pookmish** [comment]
Just change which tests are needed to pass. Remove the circleci check and add the functional GitHub actions check

**Comment by joegl** [comment]
> Just change which tests are needed to pass. Remove the circleci check and add the functional GitHub actions check

Unless you did it, it look like it updated itself automatically.

**Comment by pookmish** [comment]
I might have the other day. I can't remember

**Pull request merged**
