### PR TITLE
dropped modules and themes

### PR DESCRIPTION
**Pull request by joegl**
# READY FOR REVIEW

# Summary
- Initial clean-up of forked `stanford_profile` for `sdss_profile`
- Drops all `modules` and `themes`, replaces with `.gitkeep `file.
- The rest of the `sdss_profile` work is in #7 

# Review By (Date)
ASAP

### CODE REVIEW

**Comment by pookmish** [comment]
I don't understand what is going on here. The profile won't work without all the files being removed in this PR

**Comment by joegl** [comment]
> I don't understand what is going on here. The profile won't work without all the files being removed in this PR

Is that a new mono-repo thing for `9.x`? I assumed the modules would be pulled in via the `stanford_profile` composer requirement.

**Comment by pookmish** [comment]
No, all custom modules & themes have to be in the profile repo, except those like `stanford_migrate`. Any module that provides css/templates/content types/etc should still live inside the profile.

**Comment by joegl** [comment]
> No, all custom modules & themes have to be in the profile repo, except those like `stanford_migrate`. Any module that provides css/templates/content types/etc should still live inside the profile.

Yea that makes sense to me. When everything was in its own repo it'd get pulled into `docroot/modules/` but now since they're essentially profile specific they need to stay in the profile. I'm closing this and will re-do #7.

**Pull request closed without merging**
