### PR TITLE
Added basic public protection.

### PR DESCRIPTION
**Pull request by joegl**
# READY FOR REVIEW

# Summary
- Hide the theme from anyone without administrator or site manager roles.

### CODE REVIEW

**Review by pookmish — APPROVED** [review]
You might need to extend this just a little by either setting the public state in your CI, or checking if you're on CI in the hook

**Comment by joegl** [comment]
> You might need to extend this just a little by either setting the public state in your CI, or checking if you're on CI in the hook

Which one would you recommend? I think I'd want to set the state in the CI itself, but is that more work?

**Comment by pookmish** [comment]
Looks like the tests pass, so I guess there's no need to at this time.

**Comment by joegl** [comment]
Yea that surprised me once you pointed it out.

**Comment by joegl** [comment]
Actually, thinking about it now I don't think the `sdss_subtheme` ever gets installed in the tests.

**Comment by pookmish** [comment]
Ahh that would explain why the tests all pass. Well you don't HAVE to for your automation if you don't want. We aren't doing any Visual Regression, so the theme shouldn't make too much difference.

**Pull request merged**
